#!/usr/bin/env -S-P/usr/local/bin:/usr/bin:${PATH} php
<?php

// 自动加载处理
namespace eValor\cronTask;

use eValor\cronTask\Core\ConsoleWrite;
use eValor\cronTask\Core\Swoole;

date_default_timezone_set('Asia/Shanghai');

$loader = require_once 'vendor/autoload.php';
$loader->addPsr4('eValor\\cronTask\\', __DIR__ . DIRECTORY_SEPARATOR);

// 欢迎界面
ConsoleWrite::terminal_reset();
ConsoleWrite::color("--------------------------------------\n");
ConsoleWrite::color(" 自动签到助手 \n", ConsoleWrite::F_BLUE);
ConsoleWrite::color(" 启动时间: " . date('Y-m-d H:i:s') . PHP_EOL, ConsoleWrite::F_GREEN);
ConsoleWrite::color("--------------------------------------\n");

// 启动
$schedule = new Schedule;
$schedule->schedule();
(new Swoole)->run($schedule->cron());